# Generated by Django 4.2.16 on 2024-10-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "11499_add_editlog_resourceinstance_idx"),
        ("models", "9604_relational_data_model_handle_user_accounts"),
    ]

    operations = []
